PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX tag: <http://www.holygoat.co.uk/owl/redwood/0.1/tags/>
PREFIX api: <http://purl.org/linked-data/api/vocab#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT DATA {
    GRAPH <https://fse.ontology/> {
        # -------------------------
        # CLINICAL DOCUMENTS
        # -------------------------
        <#rad_pfiorentino>
            a fse:radiologyReport ;
            fse:body "Referto di radiologia anca paziente P. Fiorentino" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#FRNPSC56S51F839H> ;
            fse:hasHumanAuthor <tag:stardog:api:#doctor_abarese> ;
            fse:hasCustodian <tag:stardog:api:#ausl> ;
            fse:hasLatestVersion <tag:stardog:api:#rad_pfiorentino> ;
            fse:createdAt "2015-10-05T22:15:04" .
        <#vac_pfiorentino>
            a fse:immunization ;
            fse:validUntil "2022-08-01" ;
            fse:prevents obo:DOID_0080600 ;
            fse:body "Documento di avvenuta vaccinazione per COVID-19 paziente P. Fiorentino" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#FRNPSC56S51F839H> ;
            fse:hasDeviceAuthor <tag:stardog:api:#aifa_totem> ;
            fse:hasCustodian <tag:stardog:api:#aifa> ;
            fse:hasLatestVersion <tag:stardog:api:#vac_pfiorentino> ;
            fse:createdAt "2021-11-01T15:15:00" .
        <#lab_bcosta>
            a fse:laboratoryMedicineReport ;
            fse:body "Risultato esami del sangue di laboratorio paziente B. Costa" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:hasType <https://loinc.org/document-ontology/18717-9> ;
            fse:refersTo <tag:stardog:api:#CSTBRN86H62G273H> ;
            fse:hasHumanAuthor <tag:stardog:api:#nurse_alorenzo> ;
            fse:hasCustodian <tag:stardog:api:#ausl> ;
            fse:hasLatestVersion <tag:stardog:api:#lab_bcosta> ;
            fse:createdAt "2018-05-28T08:51:10" .
        <#rad_bcosta>
            a fse:radiologyReport ;
            fse:body "Referto di radiologia ulna e radio paziente B. Costa" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#CSTBRN86H62G273H> ;
            fse:hasHumanAuthor <tag:stardog:api:#doctor_aparatore> ;
            fse:hasCustodian <tag:stardog:api:#ausl> ;
            fse:hasLatestVersion <tag:stardog:api:#rad_bcosta> ;
            fse:createdAt "2008-12-24T20:14:00" .
        <#vps_bcosta>
            a fse:firstAidReport ;
            fse:body "Referto di primo soccorso paziente B. Costa" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:cameWith <tag:stardog:api:#plate_ca128td> ;
            fse:refersTo <tag:stardog:api:#CSTBRN86H62G273H> ;
            fse:hasHumanAuthor <tag:stardog:api:#nurse_gvanni> ;
            fse:hasResponsible <tag:stardog:api:#doctor_aparatore> ;
            fse:hasCustodian <tag:stardog:api:#ssn> ;
            fse:hasLatestVersion <tag:stardog:api:#vps_bcosta> ;
            fse:createdAt "2014-07-20T21:41:54" .
        <#vac_bcosta>
            a fse:immunization ;
            fse:validUntil "2022-05-05" ;
            fse:prevents obo:DOID_0080600 ;
            fse:body "Documento di avvenuta vaccinazione per COVID-19 paziente B. Costa" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#CSTBRN86H62G273H> ;
            fse:hasDeviceAuthor <tag:stardog:api:#aifa_totem> ;
            fse:hasCustodian <tag:stardog:api:#aifa> ;
            fse:hasLatestVersion <tag:stardog:api:#vac_bcosta> ;
            fse:createdAt "2021-08-08T14:12:50" .
        <#rsa_drossi>
            a fse:outpatientSpecialistReport ;
            fse:hasSpecialistReportType "Ortopedia" ;
            fse:body "Documento di ricovero in struttura RSA paziente D. Rossi" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#RSSDNI48C45C573H> ;
            fse:hasHumanAuthor <tag:stardog:api:#doctor_gmoccia> ;
            fse:hasCustodian <tag:stardog:api:#auser> ;
            fse:hasLatestVersion <tag:stardog:api:#rsa_drossi> ;
            fse:createdAt "2020-07-15T07:35:58" .
        <#vac_drossi>
            a fse:immunization ;
            fse:validUntil "2022-02-09" ;
            fse:prevents obo:DOID_0080600 ;
            fse:body "Documento di avvenuta vaccinazione per COVID-19 paziente D. Rossi" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#RSSDNI48C45C573H> ;
            fse:hasDeviceAuthor <tag:stardog:api:#aifa_totem> ;
            fse:hasCustodian <tag:stardog:api:#aifa> ;
            fse:hasLatestVersion <tag:stardog:api:#vac_drossi> ;
            fse:createdAt "2021-05-09T16:00:12" .
        <#pss_vpinto>
            a fse:summaryHealthProfile ;
            fse:includesAllergy obo:DOID_0060532 ;
            fse:includesAllergy obo:DOID_0080811 ;
            fse:includesTherapy <tag:stardog:api:#antihistamine_vpinto> ;
            fse:includesOrganDonor "true" ;
            fse:includesPregnancy <tag:stardog:api:#pregnancy_vpinto> ;
            fse:includesMedicalNotes "Allergia stagionale che si manifesta sottoforma di asma e malattia respiratoria del tratto tracheale" ;
            fse:includesDisease obo:DOID_1579 ;
            fse:body "Profilo Sanitario Sintetico paziente V. Pinto" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#VRNPNT83T45F205V> ;
            fse:hasDeviceAuthor <tag:stardog:api:#ssn_totem> ;
            fse:hasCustodian <tag:stardog:api:#ssn> ;
            fse:hasLatestVersion <tag:stardog:api:#pss_vpinto> ;
            fse:createdAt "2020-11-22T22:10:14" .
        <#ldo_fpisano>
            a fse:hospitalDischargeLetter ;
            fse:body "Documento di dimissione ospedaliera paziente F. Pisano" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#PSNFRU97L29G702B> ;
            fse:hasHumanAuthor <tag:stardog:api:#doctor_aarcuri> ;
            fse:hasCustodian <tag:stardog:api:#ordinemedici> ;
            fse:hasLatestVersion <tag:stardog:api:#ldo_fpisano> ;
            fse:createdAt "2012-10-30T14:31:21" .
        <#vac_fpisano>
            a fse:immunization ;
            fse:validUntil "2021-06-10" ;
            fse:prevents obo:DOID_0080600 ;
            fse:body "Documento di avvenuta vaccinazione per COVID-19 paziente F. Pisano" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#PSNFRU97L29G702B> ;
            fse:hasDeviceAuthor <tag:stardog:api:#aifa_totem> ;
            fse:hasCustodian <tag:stardog:api:#aifa> ;
            fse:hasLatestVersion <tag:stardog:api:#vac_fpisano> ;
            fse:createdAt "2021-05-10T10:12:40" .
        <#de_aesposito>
            a fse:exemption ;
            fse:body "Documento di esenzione paziente F. Pisano" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#SPSNMR60S42F839P> ;
            fse:hasDeviceAuthor <tag:stardog:api:#ausl_totem> ;
            fse:hasCustodian <tag:stardog:api:#ausl> ;
            fse:hasLatestVersion <tag:stardog:api:#de_aesposito> ;
            fse:createdAt "2010-10-12T14:12:35" .
        <#vac_aesposito>
            a fse:immunization ;
            fse:validUntil "2021-08-12" ;
            fse:prevents obo:DOID_0080600 ;
            fse:body "Documento di avvenuta vaccinazione per COVID-19 paziente A. Esposito" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#SPSNMR60S42F839P> ;
            fse:hasDeviceAuthor <tag:stardog:api:#aifa_totem> ;
            fse:hasCustodian <tag:stardog:api:#aifa> ;
            fse:hasLatestVersion <tag:stardog:api:#vac_aesposito> ;
            fse:createdAt "2021-07-12T09:08:14" .
        <#prescription_acalabrese>
            a fse:prescription ;
            fse:hasQuantity 2 ;
            fse:for obo:DRON_00074479 ;
            fse:body "Documento di prescrizione medica per Ventolin paziente A. Calabrese" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#CLBDLA93S07D969X> ;
            fse:hasHumanAuthor <tag:stardog:api:#doctor_aarcuri> ;
            fse:hasCustodian <tag:stardog:api:#ausl> ;
            fse:hasLatestVersion <tag:stardog:api:#prescription_acalabrese> ;
            fse:createdAt "2021-10-23T18:30:15" .
        <#vac_acalabrese>
            a fse:immunization ;
            fse:validUntil "2022-03-30" ;
            fse:prevents obo:DOID_0080600 ;
            fse:body "Documento di avvenuta vaccinazione per COVID-19 paziente A. Calabrese" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#CLBDLA93S07D969X> ;
            fse:hasDeviceAuthor <tag:stardog:api:#aifa_totem> ;
            fse:hasCustodian <tag:stardog:api:#aifa> ;
            fse:hasLatestVersion <tag:stardog:api:#vac_acalabrese> ;
            fse:createdAt "2021-06-30T15:15:23" .
        <#pss_acalabrese_1>
            a fse:summaryHealthProfile ;
            fse:includesAllergy obo:DOID_10608 ;
            fse:includesMedicalNotes "Paziente ciliaco." ;
            fse:body "Profilo Sanitario Sintetico paziente A. Calabrese" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#CLBDLA93S07D969X> ;
            fse:hasDeviceAuthor <tag:stardog:api:#ssn_totem> ;
            fse:hasCustodian <tag:stardog:api:#ssn> ;
            fse:hasLatestVersion <tag:stardog:api:#pss_acalabrese_2> ;
            fse:createdAt "2015-01-20T10:15:46" .
        <#pss_acalabrese_2>
            a fse:summaryHealthProfile ;
            fse:includesAllergy obo:DOID_10608 ;
            fse:includesAllergy obo:DOID_0040001 ;
            fse:includesDisease obo:DOID_10273 ;
            fse:includesTherapy <tag:stardog:api:#gastricacidity_acalabrese> ;
            fse:includesOrganDonor "true" ;
            fse:includesMedicalNotes "Paziente ciliaco, allergia ai gamberi. Assume regolarmente medicianale per controllare l'acidità di stomaco. Malattia cardiaca ereditaria." ;
            fse:body "Profilo Sanitario Sintetico paziente A. Calabrese" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 2 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#CLBDLA93S07D969X> ;
            fse:hasDeviceAuthor <tag:stardog:api:#ssn_totem> ;
            fse:hasCustodian <tag:stardog:api:#ssn> ;
            fse:hasLatestVersion <tag:stardog:api:#pss_acalabrese_2> ;
            fse:createdAt "2016-09-08T19:54:23" .
        <#vac_clori>
            a fse:immunization ;
            fse:validUntil "2031-05-04" ;
            fse:prevents obo:DOID_11338 ;
            fse:administration obo:DRON_00049059 ;
            fse:body "Documento di avvenuta vaccinazione per Tetano paziente C. Clori" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#LROCAI84C04G702E> ;
            fse:hasDeviceAuthor <tag:stardog:api:#aifa_totem> ;
            fse:hasCustodian <tag:stardog:api:#aifa> ;
            fse:hasLatestVersion <tag:stardog:api:#vac_clori> ;
            fse:createdAt "2021-05-04T17:08:54" .
        <#pss_clori>
            a fse:summaryHealthProfile ;
            fse:includesAllergy obo:DOID_0050133 ;
            fse:includesDisease obo:DOID_0060118 ;
            fse:includesTherapy <tag:stardog:api:#fugalinfectiontreatment_clori> ;
            fse:includesOrganDonor "false" ;
            fse:includesMedicalNotes "Grave infezione da funghi che si manifesta con escoriazioni sulla pelle del paziente. Malformazione cavità toracica." ;
            fse:body "Profilo Sanitario Sintetico paziente C. Clori" ;
            fse:languageCode "it-IT" ;
            fse:realmCode "IT" ;
            fse:versionNumber 1 ;
            fse:confidentialityCode "N" ;
            fse:refersTo <tag:stardog:api:#LROCAI84C04G702E> ;
            fse:hasDeviceAuthor <tag:stardog:api:#ssn_totem> ;
            fse:hasCustodian <tag:stardog:api:#ssn> ;
            fse:hasLatestVersion <tag:stardog:api:#pss_clori> ;
            fse:createdAt "2017-08-14T15:34:45" .
        # -------------------------
        # PREGNANCIES
        # -------------------------
        <#pregnancy_vpinto>
            a fse:pregnancy ;
            fse:startedAt "2003-01-01" ;
            fse:endedAt "2003-09-27" ;
            fse:result "true" .
        # -------------------------
        # THERAPIES
        # -------------------------
        <#antihistamine_vpinto>
            a fse:therapy ;
            fse:startDate "2021-09-24" ;
            fse:dailyQuantity 1 ;
            fse:hasMedicinal obo:DRON_00070584 .
        <#fugalinfectiontreatment_clori>
            a fse:therapy ;
            fse:startDate "2021-08-08" ;
            fse:dailyQuantity 2 ;
            fse:hasMedicinal obo:CHEBI_10023 .
        <#gastricacidity_acalabrese>
            a fse:therapy ;
            fse:startDate "2021-09-10" ;
            fse:dailyQuantity 2 ;
            fse:hasMedicinal obo:CHEBI_55324 .
        # -------------------------
        # DEVICES
        # -------------------------
        <#ultron>
            a fse:device ;
            fse:hasIdentifier "ultron" .
        <#ssn_totem>
            a fse:device ;
            fse:hasIdentifier "ssn_totem" .
        <#ausl_totem>
            a fse:device ;
            fse:hasIdentifier "ausl_totem" .
        <#aifa_totem>
            a fse:device ;
            fse:hasIdentifier "aifa_totem" .
        # -------------------------
        # VEHICLES
        # -------------------------
        <#plate_ca128td>
            a fse:vehicle ;
            fse:plate "CA128TD" .
        <#plate_de843pr>
            a fse:vehicle ;
            fse:plate "DE843PR" .
        # -------------------------
        # PATIENTS
        # -------------------------
        <#FRNPSC56S51F839H>
            a fse:patient ;
            foaf:firstName "Priscilla" ;
            foaf:lastName "Fiorentino" ;
            foaf:birthday "11/11/1956" ;
            fse:fiscalCode "FRNPSC56S51F839H" ;
            fse:healthCardNumber "80380800301569845351" ;
            fse:hasFamilyDoctor <tag:stardog:api:#doctor_abarese> .
        <#RSSDNI48C45C573H>
            a fse:patient ;
            foaf:firstName "Diana" ;
            foaf:lastName "Rossi" ;
            foaf:birthday "05/03/1948" ;
            fse:fiscalCode "RSSDNI48C45C573H" ;
            fse:healthCardNumber "80380800308945237892" .
        <#CSTBRN86H62G273H>
            a fse:patient ;
            foaf:firstName "Bruna" ;
            foaf:lastName "Costa" ;
            foaf:birthday "22/06/1986" ;
            fse:fiscalCode "CSTBRN86H62G273H" ;
            fse:healthCardNumber "80380800304875162594" ;
            fse:hasFamilyDoctor <tag:stardog:api:#doctor_abarese> .
        <#VRNPNT83T45F205V>
            a fse:patient ;
            foaf:firstName "Veronica" ;
            foaf:lastName "Pinto" ;
            foaf:birthday "05/12/1983" ;
            fse:fiscalCode "VRNPNT83T45F205V" ;
            fse:healthCardNumber "80380800301126596519" .
        <#PSNFRU97L29G702B>
            a fse:patient ;
            foaf:firstName "Furio" ;
            foaf:lastName "Pisano" ;
            foaf:birthday "29/07/1997" ;
            fse:fiscalCode "PSNFRU97L29G702B" ;
            fse:healthCardNumber "803808003099956423156" .
        <#SPSNMR60S42F839P>
            a fse:patient ;
            foaf:firstName "Anna Maria" ;
            foaf:lastName "Esposito" ;
            foaf:birthday "02/11/1960" ;
            fse:fiscalCode "SPSNMR60S42F839P" ;
            fse:healthCardNumber "803808003045876589452" .
        <#CLBDLA93S07D969X>
            a fse:patient ;
            foaf:firstName "Adele" ;
            foaf:lastName "Calabresi" ;
            foaf:birthday "07/11/1993" ;
            fse:fiscalCode "CLBDLA93S07D969X" ;
            fse:healthCardNumber "803808003087512326896" ;
            fse:hasFamilyDoctor <tag:stardog:api:#doctor_aarcuri> .
        <#LROCAI84C04G702E>
            a fse:patient ;
            foaf:firstName "Caio" ;
            foaf:lastName "Lori" ;
            foaf:birthday "04/03/1984" ;
            fse:fiscalCode "LROCAI84C04G702E" ;
            fse:healthCardNumber "803808003045852135897" .
        # -------------------------
        # HEALTH WORKERS
        # -------------------------
        <#clucchese>
            a fse:healthWorker ;
            fse:worksIn <tag:stardog:api:#sedeaifa> ;
            foaf:firstName "Cosimo" ;
            foaf:lastName "Lucchese" ;
            foaf:birthday "16/08/1963" .
        <#dtrentino>
            a fse:healthWorker ;
            fse:worksIn <tag:stardog:api:#ospedalembufalini> ;
            foaf:firstName "Divo" ;
            foaf:lastName "Trentino" ;
            foaf:birthday "06/04/1993" .
        # -------------------------
        # DOCTORS
        # -------------------------
        <#doctor_abarese>
            a fse:doctor ;
            foaf:firstName "Antonia" ;
            foaf:lastName "Barese" ;
            foaf:birthday "11/07/1977" ;
            fse:belongsTo <tag:stardog:api:#ordinemedici> .
        <#doctor_aarcuri>
            a fse:doctor ;
            foaf:firstName "Ambrosino" ;
            foaf:lastName "Arcuri" ;
            foaf:birthday "17/07/1966" ;
            fse:belongsTo <tag:stardog:api:#ordinemedici> .
        <#doctor_cbelotti>
            a fse:doctor ;
            foaf:firstName "Carlotta" ;
            foaf:lastName "Belotti" ;
            foaf:birthday "06/06/1967" ;
            fse:belongsTo <tag:stardog:api:#aifa> .
        <#doctor_aparatore>
            a fse:doctor ;
            foaf:firstName "Alessandro" ;
            foaf:lastName "Paratore" ;
            foaf:birthday "22/10/1959" ;
            fse:belongsTo <tag:stardog:api:#ssn> .
        <#doctor_gmoccia>
            a fse:doctor ;
            foaf:firstName "Giovanni" ;
            foaf:lastName "Moccia" ;
            foaf:birthday "12/08/1974" ;
            fse:belongsTo <tag:stardog:api:#auser> .
        # -------------------------
        # NURSES
        # -------------------------
        <#nurse_alorenzo>
            a fse:nurse ;
            foaf:firstName "Alfredina" ;
            foaf:lastName "Lorenzo" ;
            foaf:birthday "18/01/1959" ;
            fse:belongsTo <tag:stardog:api:#ausl> .
        <#nurse_acocci>
            a fse:nurse ;
            foaf:firstName "Aldino" ;
            foaf:lastName "Cocci" ;
            foaf:birthday "15/12/1988" ;
            fse:belongsTo <tag:stardog:api:#ausl> .
        <#nurse_gvanni>
            a fse:nurse ;
            foaf:firstName "Giorgio" ;
            foaf:lastName "Vanni" ;
            foaf:birthday "15/02/1985" ;
            fse:belongsTo <tag:stardog:api:#ssn> .
        <#nurse_cvanto>
            a fse:nurse ;
            foaf:firstName "Camilla" ;
            foaf:lastName "Vanto" ;
            foaf:birthday "23/03/1980" ;
            fse:belongsTo <tag:stardog:api:#auser> .
        <#nurse_mroccia>
            a fse:nurse ;
            foaf:firstName "Michele" ;
            foaf:lastName "Roccia" ;
            foaf:birthday "12/10/1984" ;
            fse:belongsTo <tag:stardog:api:#auser> .
        # -------------------------
        # HEALTH ORGANIZATIONS
        # -------------------------
        <#ordinemedici>
            a fse:healthOrganization ;
            org:identifier "Ordine dei Medici Chirurghi e Odontoiatri Italiana" ;
            org:hasSite <tag:stardog:api:#ufficiodoctor_abarese> ;
            org:hasSite <tag:stardog:api:#ufficiodoctor_cbelotti> .
        <#ausl>
            a fse:healthOrganization ;
            org:identifier "Azienda Unità Sanitaria Locale" ;
            org:hasSite <tag:stardog:api:#sedeauslfc> ;
            org:hasSite <tag:stardog:api:#sedelegaleusl> .
        <#aifa>
            a fse:healthOrganization ;
            org:identifier "Agenzia Italiana del Farmaco" ;
            org:hasSite <tag:stardog:api:#sedeaifa> .
        <#auser>
            a fse:healthOrganization ;
            org:identifier "Associazione per l'invecchiamento attivo" ;
            org:hasSite <tag:stardog:api:#rsabellora> ;
            org:hasSite <tag:stardog:api:#rsamonsavano> .
        <#ssn>
            a fse:healthOrganization ;
            org:identifier "Servizio Sanitario Nazionale" ;
            org:hasSite <tag:stardog:api:#ospedalembufalini> ;
            org:hasSite <tag:stardog:api:#ospedalesanraffaele> .
        # -------------------------
        # HEALTHCARE FACILITY
        # -------------------------
        <#sedeauslfc>
            a fse:healthcareFacility ;
            org:siteAddress "Via della Rocca, 19 - Forlì" .
        <#sedelegaleusl>
            a fse:healthcareFacility ;
            org:siteAddress "Via Castiglione, 29 -Bologna" .
        <#ospedalembufalini>
            a fse:healthcareFacility ;
            org:siteAddress "Viale Giovanni Ghirotti, 286 - Cesena" .
        <#ospedalesanraffaele>
            a fse:healthcareFacility ;
            org:siteAddress "Via Olgettina, 60 - Milano" .
        <#ufficiodoctor_cbelotti>
            a fse:healthcareFacility ;
            org:siteAddress "Via dell'Acquedotto, 31 - Perugia" .
        <#ufficiodoctor_abarese>
            a fse:healthcareFacility ;
            org:siteAddress "Via Cervese, 1 - Forlì" .
        <#sedeaifa>
            a fse:healthcareFacility ;
            org:siteAddress "Via del Tritone, 181 - Roma" .
        <#rsabellora>
            a fse:healthcareFacility ;
            org:siteAddress "Piazza Giovine Italia, 1 - Gallarate" .
        <#rsamonsavano>
            a fse:healthcareFacility ;
            org:siteAddress "Via Fortuna, 1 - San Francesco" .
        # -------------------------
        # LABORATORIES
        # -------------------------
        <#lab_bianalisi>
            a fse:laboratory ;
            org:siteAddress "Via Maceri, 12 - Forlì" .
        <#lab_pavese>
            a fse:laboratory ;
            org:siteAddress "Via Pavese, 410 - Roma" .
        <#lab_synlab>
            a fse:laboratory ;
            org:siteAddress "Via Zuccherificio, 153 - Cesena" .
    }
}